name: intern
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4
dependencies:
  flutter:
      sdk: flutter
  flutter_localizations:
      sdk: flutter
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.16
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  shared_preferences: ^2.3.4
  connectivity_plus: ^6.1.1
  flutter_rating_bar: ^4.0.1
  responsive_grid_list: ^1.4.0
  google_maps_flutter: ^2.10.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/fonts/PoppinsBold.ttf
          weight: 700
        - asset: assets/fonts/PoppinsMedium.ttf
          weight: 500
